package com.ngc.CLQA.entities;
// Generated Mar 20, 2018 10:08:45 AM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * QauiQuestions generated by hbm2java
 */
public class QauiQuestions implements java.io.Serializable {

	private BigDecimal questionDbid;
	private QauiSections qauiSections;
	private String questionId;
	private String questionText;
	private String answerInstructions;
	private String additionalInstructions;
	private Boolean nonCommercial;
	private String questionLabel;
	private BigDecimal minimumSelections;
	private BigDecimal maximumSelections;
	private Boolean containsNoneOfTheAbove;
	private Blob questionSequenceType;
	private String defaultNextQuestionId;
	private String conditions;
	private Boolean isDisabled;
	private Set qauiMovedQuestionses = new HashSet(0);
	private Set qauiAnswerses = new HashSet(0);

	public QauiQuestions() {
	}

	public QauiQuestions(BigDecimal questionDbid, QauiSections qauiSections, String questionId, String questionText) {
		this.questionDbid = questionDbid;
		this.qauiSections = qauiSections;
		this.questionId = questionId;
		this.questionText = questionText;
	}

	public QauiQuestions(BigDecimal questionDbid, QauiSections qauiSections, String questionId, String questionText,
			String answerInstructions, String additionalInstructions, Boolean nonCommercial, String questionLabel,
			BigDecimal minimumSelections, BigDecimal maximumSelections, Boolean containsNoneOfTheAbove,
			Blob questionSequenceType, String defaultNextQuestionId, String conditions, Boolean isDisabled,
			Set qauiMovedQuestionses, Set qauiAnswerses) {
		this.questionDbid = questionDbid;
		this.qauiSections = qauiSections;
		this.questionId = questionId;
		this.questionText = questionText;
		this.answerInstructions = answerInstructions;
		this.additionalInstructions = additionalInstructions;
		this.nonCommercial = nonCommercial;
		this.questionLabel = questionLabel;
		this.minimumSelections = minimumSelections;
		this.maximumSelections = maximumSelections;
		this.containsNoneOfTheAbove = containsNoneOfTheAbove;
		this.questionSequenceType = questionSequenceType;
		this.defaultNextQuestionId = defaultNextQuestionId;
		this.conditions = conditions;
		this.isDisabled = isDisabled;
		this.qauiMovedQuestionses = qauiMovedQuestionses;
		this.qauiAnswerses = qauiAnswerses;
	}

	public BigDecimal getQuestionDbid() {
		return this.questionDbid;
	}

	public void setQuestionDbid(BigDecimal questionDbid) {
		this.questionDbid = questionDbid;
	}

	public QauiSections getQauiSections() {
		return this.qauiSections;
	}

	public void setQauiSections(QauiSections qauiSections) {
		this.qauiSections = qauiSections;
	}

	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	public String getQuestionText() {
		return this.questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	public String getAnswerInstructions() {
		return this.answerInstructions;
	}

	public void setAnswerInstructions(String answerInstructions) {
		this.answerInstructions = answerInstructions;
	}

	public String getAdditionalInstructions() {
		return this.additionalInstructions;
	}

	public void setAdditionalInstructions(String additionalInstructions) {
		this.additionalInstructions = additionalInstructions;
	}

	public Boolean getNonCommercial() {
		return this.nonCommercial;
	}

	public void setNonCommercial(Boolean nonCommercial) {
		this.nonCommercial = nonCommercial;
	}

	public String getQuestionLabel() {
		return this.questionLabel;
	}

	public void setQuestionLabel(String questionLabel) {
		this.questionLabel = questionLabel;
	}

	public BigDecimal getMinimumSelections() {
		return this.minimumSelections;
	}

	public void setMinimumSelections(BigDecimal minimumSelections) {
		this.minimumSelections = minimumSelections;
	}

	public BigDecimal getMaximumSelections() {
		return this.maximumSelections;
	}

	public void setMaximumSelections(BigDecimal maximumSelections) {
		this.maximumSelections = maximumSelections;
	}

	public Boolean getContainsNoneOfTheAbove() {
		return this.containsNoneOfTheAbove;
	}

	public void setContainsNoneOfTheAbove(Boolean containsNoneOfTheAbove) {
		this.containsNoneOfTheAbove = containsNoneOfTheAbove;
	}

	public Blob getQuestionSequenceType() {
		return this.questionSequenceType;
	}

	public void setQuestionSequenceType(Blob questionSequenceType) {
		this.questionSequenceType = questionSequenceType;
	}

	public String getDefaultNextQuestionId() {
		return this.defaultNextQuestionId;
	}

	public void setDefaultNextQuestionId(String defaultNextQuestionId) {
		this.defaultNextQuestionId = defaultNextQuestionId;
	}

	public String getConditions() {
		return this.conditions;
	}

	public void setConditions(String conditions) {
		this.conditions = conditions;
	}

	public Boolean getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	public Set getQauiMovedQuestionses() {
		return this.qauiMovedQuestionses;
	}

	public void setQauiMovedQuestionses(Set qauiMovedQuestionses) {
		this.qauiMovedQuestionses = qauiMovedQuestionses;
	}

	public Set getQauiAnswerses() {
		return this.qauiAnswerses;
	}

	public void setQauiAnswerses(Set qauiAnswerses) {
		this.qauiAnswerses = qauiAnswerses;
	}

}
