package com.ngc.CLQA.entities;
// Generated Mar 20, 2018 10:08:45 AM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QauiSections generated by hbm2java
 */
@Entity
@Table(name="QAUI_SECTIONS")
public class QauiSections implements java.io.Serializable {

	private BigDecimal sectionDbid;
	private Integer documentDbid;
	private String sectionName;
	private Boolean validated;
	private Boolean errors;
	private Boolean nonCommercial;
//	private Set qauiQuestionses = new HashSet(0);
//	private Set qauiMovedQuestionsesForDestinationSectionId = new HashSet(0);
//	private Set qauiMovedQuestionsesForSourceSectionId = new HashSet(0);

	public QauiSections() {
	}

	
	public QauiSections(BigDecimal sectionDbid, Integer documentDbid, String sectionName) {
		this.sectionDbid = sectionDbid;
		this.documentDbid = documentDbid;
		this.sectionName = sectionName;
	}

	
	public QauiSections(BigDecimal sectionDbid, Integer documentDbid, String sectionName, Boolean validated,
			Boolean errors, Boolean nonCommercial 
			) {
		this.sectionDbid = sectionDbid;
		this.documentDbid = documentDbid;
		this.sectionName = sectionName;
		this.validated = validated;
		this.errors = errors;
		this.nonCommercial = nonCommercial;
	}

	@Id
	@Column(name="SECTION_DBID")
	public BigDecimal getSectionDbid() {
		return this.sectionDbid;
	}

	public void setSectionDbid(BigDecimal sectionDbid) {
		this.sectionDbid = sectionDbid;
	}

	
	@Column(name="DOCUMENT_DBID")
	public Integer getDocumentDbid() {
		return this.documentDbid;
	}

	public void setDocumentDbid(Integer documentDbid) {
		this.documentDbid = documentDbid;
	}

	@Column(name="SECTION_NAME")
	public String getSectionName() {
		return this.sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	@Column(name="VALIDATED")
	public Boolean getValidated() {
		return this.validated;
	}

	public void setValidated(Boolean validated) {
		this.validated = validated;
	}

	@Column(name="ERRORS")
	public Boolean getErrors() {
		return this.errors;
	}

	public void setErrors(Boolean errors) {
		this.errors = errors;
	}

	@Column(name="NON_COMMERCIAL")
	public Boolean getNonCommercial() {
		return this.nonCommercial;
	}

	public void setNonCommercial(Boolean nonCommercial) {
		this.nonCommercial = nonCommercial;
	}

//	public Set getQauiQuestionses() {
//		return this.qauiQuestionses;
//	}

//	public void setQauiQuestionses(Set qauiQuestionses) {
//		this.qauiQuestionses = qauiQuestionses;
//	}

//	public Set getQauiMovedQuestionsesForDestinationSectionId() {
//		return this.qauiMovedQuestionsesForDestinationSectionId;
//	}

//	public void setQauiMovedQuestionsesForDestinationSectionId(Set qauiMovedQuestionsesForDestinationSectionId) {
//		this.qauiMovedQuestionsesForDestinationSectionId = qauiMovedQuestionsesForDestinationSectionId;
//	}

//	public Set getQauiMovedQuestionsesForSourceSectionId() {
//		return this.qauiMovedQuestionsesForSourceSectionId;
//	}

//	public void setQauiMovedQuestionsesForSourceSectionId(Set qauiMovedQuestionsesForSourceSectionId) {
//		this.qauiMovedQuestionsesForSourceSectionId = qauiMovedQuestionsesForSourceSectionId;
//	}

}
