package com.ngc.CLQA.entities;
// Generated Mar 20, 2018 10:08:45 AM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QauiPathValues generated by hbm2java
 */
@Entity
@Table(name="QAUI_PATH_VALUES")
public class QauiPathValues implements java.io.Serializable {

	private BigDecimal dbid;
	private Integer answerReference;
	private String path;
	private String value;

	public QauiPathValues() {
	}

	public QauiPathValues(BigDecimal dbid, Integer answerReference) {
		this.dbid = dbid;
		this.answerReference = answerReference;
	}

	public QauiPathValues(BigDecimal dbid, Integer answerReference, String path, String value) {
		this.dbid = dbid;
		this.answerReference = answerReference;
		this.path = path;
		this.value = value;
	}

	@Id
	@Column(name="DBID")
	public BigDecimal getDbid() {
		return this.dbid;
	}

	public void setDbid(BigDecimal dbid) {
		this.dbid = dbid;
	}

	@Column(name="ANSWER_REFERENCE")
	public Integer getAnswerReference() {
		return this.answerReference;
	}

	public void setAnswerReference(Integer answerReference) {
		this.answerReference = answerReference;
	}

	@Column(name="PATH")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name="VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
