package com.ngc.CLQA.entities;
// Generated Mar 20, 2018 10:08:45 AM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * QauiDocuments generated by hbm2java
 */
@Entity
@Table(name="QAUI_DOCUMENTS")
public class QauiDocuments implements java.io.Serializable {

	private Integer documentDbid;
	private String documentId;
	private String creationDate;
	private String lastUpdate;
	private String apiRequestSchemaVersion;
	private Boolean finalized;
	private String editHistory;
//	private Set qauiEditLogs = new HashSet(0);
//	private Set qauiSectionses = new HashSet(0);
//	private Set qauiMovedQuestionses = new HashSet(0);

	public QauiDocuments() {
	}

	public QauiDocuments(Integer documentDbid, String documentId, String apiRequestSchemaVersion) {
		this.documentDbid = documentDbid;
		this.documentId = documentId;
		this.apiRequestSchemaVersion = apiRequestSchemaVersion;
	}

	public QauiDocuments(Integer documentDbid, String documentId, String creationDate, String lastUpdate,
			String apiRequestSchemaVersion, Boolean finalized, String editHistory 
//			Set qauiEditLogs, 
//			Set qauiSectionses,
//			Set qauiMovedQuestionses
			) {
		this.documentDbid = documentDbid;
		this.documentId = documentId;
		this.creationDate = creationDate;
		this.lastUpdate = lastUpdate;
		this.apiRequestSchemaVersion = apiRequestSchemaVersion;
		this.finalized = finalized;
		this.editHistory = editHistory;
//		this.qauiEditLogs = qauiEditLogs;
//		this.qauiSectionses = qauiSectionses;
//		this.qauiMovedQuestionses = qauiMovedQuestionses;
	}

	@Column(name="DOCUMENT_DBID")
	public Integer getDocumentDbid() {
		return this.documentDbid;
	}

	public void setDocumentDbid(Integer documentDbid) {
		this.documentDbid = documentDbid;
	}

	@Id
	@Column(name="DOCUMENT_ID")
	public String getDocumentId() {
		return this.documentId;
	}

	
	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	@Column(name="CREATION_DATE")
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name="LAST_UPDATE")
	public String getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(String lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name="API_REQUEST_SCHEMA_VERSION")
	public String getApiRequestSchemaVersion() {
		return this.apiRequestSchemaVersion;
	}

	public void setApiRequestSchemaVersion(String apiRequestSchemaVersion) {
		this.apiRequestSchemaVersion = apiRequestSchemaVersion;
	}

	@Column(name="FINALIZED")
	public Boolean getFinalized() {
		return this.finalized;
	}

	public void setFinalized(Boolean finalized) {
		this.finalized = finalized;
	}

	@Column(name="EDIT_HISTORY")
	public String getEditHistory() {
		return this.editHistory;
	}

	public void setEditHistory(String editHistory) {
		this.editHistory = editHistory;
	}

//	public Set getQauiEditLogs() {
//		return this.qauiEditLogs;
//	}
//
//	public void setQauiEditLogs(Set qauiEditLogs) {
//		this.qauiEditLogs = qauiEditLogs;
//	}
//
//	public Set getQauiSectionses() {
//		return this.qauiSectionses;
//	}
//
//	public void setQauiSectionses(Set qauiSectionses) {
//		this.qauiSectionses = qauiSectionses;
//	}
//
//	public Set getQauiMovedQuestionses() {
//		return this.qauiMovedQuestionses;
//	}
//
//	public void setQauiMovedQuestionses(Set qauiMovedQuestionses) {
//		this.qauiMovedQuestionses = qauiMovedQuestionses;
//	}

}
