package com.ngc.CLQA.entities;
// Generated Mar 20, 2018 10:08:45 AM by Hibernate Tools 5.2.8.Final

/**
 * QauiConditions generated by hbm2java
 */
public class QauiConditions implements java.io.Serializable {

	private QauiConditionsId id;

	public QauiConditions() {
	}

	public QauiConditions(QauiConditionsId id) {
		this.id = id;
	}

	public QauiConditionsId getId() {
		return this.id;
	}

	public void setId(QauiConditionsId id) {
		this.id = id;
	}

}
